# Generated by Django 5.2.3 on 2025-06-23 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_registration_confirm_password_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
